<?php
$excel->getActiveSheet()
    ->getStyle('A1')
    ->getFill()
    ->setFillType(PHPExcel_Style_Fill::FILL_SOLID)
    ->getStartColor()
    ->setRGB('7FFFD4');
$excel->getActiveSheet()
    ->getStyle('B1')
    ->getFill()
    ->setFillType(PHPExcel_Style_Fill::FILL_SOLID)
    ->getStartColor()
    ->setRGB('7FFFD4');
$excel->getActiveSheet()
    ->getStyle('C1')
    ->getFill()
    ->setFillType(PHPExcel_Style_Fill::FILL_SOLID)
    ->getStartColor()
    ->setRGB('7FFFD4');
$excel->getActiveSheet()
    ->getStyle('D1')
    ->getFill()
    ->setFillType(PHPExcel_Style_Fill::FILL_SOLID)
    ->getStartColor()
    ->setRGB('7FFFD4');
$excel->getActiveSheet()
    ->getStyle('E1')
    ->getFill()
    ->setFillType(PHPExcel_Style_Fill::FILL_SOLID)
    ->getStartColor()
    ->setRGB('7FFFD4');
$excel->getActiveSheet()
    ->getStyle('F1')
    ->getFill()
    ->setFillType(PHPExcel_Style_Fill::FILL_SOLID)
    ->getStartColor()
    ->setRGB('7FFFD4');
$excel->getActiveSheet()
    ->getStyle('G1')
    ->getFill()
    ->setFillType(PHPExcel_Style_Fill::FILL_SOLID)
    ->getStartColor()
    ->setRGB('7FFFD4');
?>