<?php
$excel->getActiveSheet()
    ->getStyle('A3')
    ->getFill()
    ->setFillType(PHPExcel_Style_Fill::FILL_SOLID)
    ->getStartColor()
    ->setRGB('90EE90');
$excel->getActiveSheet()
    ->getStyle('B3')
    ->getFill()
    ->setFillType(PHPExcel_Style_Fill::FILL_SOLID)
    ->getStartColor()
    ->setRGB('90EE90');
$excel->getActiveSheet()
    ->getStyle('C3')
    ->getFill()
    ->setFillType(PHPExcel_Style_Fill::FILL_SOLID)
    ->getStartColor()
    ->setRGB('90EE90');
$excel->getActiveSheet()
    ->getStyle('D3')
    ->getFill()
    ->setFillType(PHPExcel_Style_Fill::FILL_SOLID)
    ->getStartColor()
    ->setRGB('90EE90');
$excel->getActiveSheet()
    ->getStyle('E3')
    ->getFill()
    ->setFillType(PHPExcel_Style_Fill::FILL_SOLID)
    ->getStartColor()
    ->setRGB('90EE90');
$excel->getActiveSheet()
    ->getStyle('F3')
    ->getFill()
    ->setFillType(PHPExcel_Style_Fill::FILL_SOLID)
    ->getStartColor()
    ->setRGB('90EE90');
?>