<?php
$excel->getActiveSheet()
    ->getStyle('A1')
    ->getFill()
    ->setFillType(PHPExcel_Style_Fill::FILL_SOLID)
    ->getStartColor()
    ->setRGB('ADFF2F');
$excel->getActiveSheet()
    ->getStyle('B1')
    ->getFill()
    ->setFillType(PHPExcel_Style_Fill::FILL_SOLID)
    ->getStartColor()
    ->setRGB('ADFF2F');
$excel->getActiveSheet()
    ->getStyle('C1')
    ->getFill()
    ->setFillType(PHPExcel_Style_Fill::FILL_SOLID)
    ->getStartColor()
    ->setRGB('ADFF2F');
$excel->getActiveSheet()
    ->getStyle('D1')
    ->getFill()
    ->setFillType(PHPExcel_Style_Fill::FILL_SOLID)
    ->getStartColor()
    ->setRGB('ADFF2F');
?>